name: Playwright Test CI
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Add required variable to .env file
        run: |
          echo "BASE_URL = ${{ vars.BASE_URL }}" >> .env
          echo "API_BASE_URL = ${{ vars.API_BASE_URL }}" >> .env
          echo "EMAIL_ADMIN = ${{ vars.EMAIL_ADMIN }}" >> .env
          echo "PASS_ADMIN = ${{ vars.PASS_ADMIN }}" >> .env

      - name: Build Docker image
        run: docker build -t pom-kasiraja .

      - name: Debug node_modules
        run: ls -la node_modules/@playwright/test

      - name: Run Playwright tests in Docker
        run: docker run --rm -v ${{ github.workspace }}:/app -w /app pom-kasiraja npx playwright test --reporter=html

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATEDSA }}
      - name: Check SSH folder content
        run: ls -la ~/.ssh
      - name: Check NodeJS version
        run: node -v
      - name: rsync connection
        run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc * ${{secrets.USERDEV}}@${{secrets.SERVERDEV}}:/home/unang/pom-kasiraja-github/
